/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GameManager__factory } from "./GameManager__factory";
export { IERC721Mintable__factory } from "./IERC721Mintable__factory";
