/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gameManagerSol from "./GameManager.sol";
export type { gameManagerSol };
export type { NFT } from "./NFT";
